# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QPoint
from PyQt5.QtGui import QColor
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed
            )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth()
            )
        MainWindow.setFixedSize(310, 240)
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(
            "C:\\Python\\Curso_Python\\PYQT_Aulas\\imgs\\\
                outline_calculate_black_24dp.png")
        MainWindow.setWindowIcon(icon)
        # MainWindow.setStyleSheet('background-color: #494C51; color: #FFFFFF')
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background-color: #353A40;\
        color: white')
        self.centralwidget.setObjectName("centralwidget")
        self.boxSaida = QtWidgets.QComboBox(self.centralwidget)
        self.boxSaida.setGeometry(QtCore.QRect(10, 80, 281, 18))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.boxSaida.setFont(font)
        self.boxSaida.setStyleSheet("background-color: white;\
            color: #494C51; border-radius: 3px")
        self.boxSaida.setObjectName("boxSaida")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.lineValorIn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineValorIn.setGeometry(QtCore.QRect(10, 120, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.lineValorIn.setFont(font)
        self.boxSaida.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineValorIn.setStyleSheet("background-color: white;\
            color: #494C51; border-radius: 3px")
        self.lineValorIn.setText("")
        self.lineValorIn.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineValorIn.setObjectName("lineValorIn")
        self.btnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.btnConvert.setGeometry(QtCore.QRect(210, 120, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btnConvert.setFont(font)
        self.btnConvert.setStyleSheet(
            "QPushButton{background-color: #0083F9;\
            color: white; border-radius: 3px;}"
            "QPushButton::hover{background-color: #1951DF;}"
            )
        self.btnConvert.setObjectName("btnConvert")
        self.boxEntrada = QtWidgets.QComboBox(self.centralwidget)
        self.boxEntrada.setGeometry(QtCore.QRect(10, 40, 281, 18))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.boxEntrada.setFont(font)
        self.boxEntrada.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boxEntrada.setStyleSheet("background-color: white;\
             color: #494C51; border-radius: 3px")
        self.boxEntrada.setObjectName("boxEntrada")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.lineResultado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineResultado.setGeometry(QtCore.QRect(9, 160, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        self.lineResultado.setFont(font)
        self.lineResultado.setStyleSheet("background-color: #212429;\
                    color: #F8F9FB")
        self.lineResultado.setText("")
        self.lineResultado.setReadOnly(True)
        self.lineResultado.setObjectName("lineResultado")
        self.lineResultado.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 21))
        self.menubar.setStyleSheet(
            'QMenuBar {background-color: #494C51; color: white;}'
            'QMenuBar::item::selected {border: 1px solid black;\
                background-color: #353A40; color: #0083F9;}'
            'QMenu {background-color: #494C51; color: white}'
            'QMenu::item::selected {border: 0.5px solid black;\
                background-color: #353A40; color: #0083F9 }'
                    )
        self.menubar.setObjectName("menubar")
        self.menuTipo_de_dado = QtWidgets.QMenu(self.menubar)
        self.menuTipo_de_dado.setObjectName("menuTipo_de_dado")
        MainWindow.setMenuBar(self.menubar)
        self.actionDados_de_arm = QtWidgets.QAction(MainWindow)
        self.actionDados_de_arm.setObjectName("actionDados_de_arm")
        self.actionMoeda = QtWidgets.QAction(MainWindow)
        self.actionMoeda.setObjectName("actionMoeda")
        self.actionMetrico = QtWidgets.QAction(MainWindow)
        self.actionMetrico.setObjectName("actionMetrico")
        self.menuTipo_de_dado.addAction(self.actionDados_de_arm)
        self.menuTipo_de_dado.addAction(self.actionMoeda)
        self.menuTipo_de_dado.addAction(self.actionMetrico)
        self.menubar.addAction(self.menuTipo_de_dado.menuAction())

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: #353A40; color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.currentActive = 'dado'
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        for child in self.findChildren(QtWidgets.QWidget):
            effect = QGraphicsDropShadowEffect(
                offset=QPoint(0, 3), blurRadius=3, color=QColor("#2C3137")
            )
            if 'QLabel' not in (type(child).__name__):
                child.setGraphicsEffect(effect)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Conversor de medidas"))
        self.boxSaida.setItemText(0, _translate(
            "MainWindow", "Escolha o tipo de saida"))
        self.boxSaida.setItemText(1, _translate("MainWindow", "MB"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "KB"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "Kb"))
        self.lineValorIn.setPlaceholderText(_translate(
            "MainWindow", "Insira um valor"))
        self.btnConvert.setText(_translate("MainWindow", "CONVERTER"))
        self.boxEntrada.setItemText(0, _translate(
            "MainWindow", "Escolha o tipo de entrada"))
        self.boxEntrada.setItemText(1, _translate("MainWindow", "MB"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "KB"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "Kb"))
        self.lineResultado.setPlaceholderText(_translate(
            "MainWindow", "Resultado"))
        self.menuTipo_de_dado.setTitle(_translate(
            "MainWindow", "Tipo de dado"))
        self.actionDados_de_arm.setText(_translate(
            "MainWindow", "Dados de arm."))
        self.actionMoeda.setText(_translate("MainWindow", "Moeda"))
        self.actionMetrico.setText(_translate("MainWindow", "Metrico"))
        self.label.setText(_translate("MainWindow", "CONVERTER DADOS"))

    def altera_dados(self):
        _translate = QtCore.QCoreApplication.translate
        # Alteração das informações de entrada
        self.boxEntrada.setItemText(1, _translate("MainWindow", "MB"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "KB"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "Kb"))
        # Alteração das informações de saida
        self.boxSaida.setItemText(1, _translate("MainWindow", "MB"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "KB"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "Kb"))
        # Variavel de controle
        self.currentActive = 'dado'
        self.label.setText(_translate("MainWindow", "CONVERTER DADOS"))

    def altera_moedas(self):
        _translate = QtCore.QCoreApplication.translate
        # Alteração das informações de entrada
        self.boxSaida.setItemText(1, _translate("MainWindow", "BRL"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "USD"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "JPY"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "EUR"))
        # Alteração das informações de entrada
        self.boxEntrada.setItemText(1, _translate("MainWindow", "BRL"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "USD"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "JPY"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "EUR"))
        # Variavel de controle
        self.currentActive = 'moeda'
        self.label.setText(_translate("MainWindow", "CONVERTER MOEDAS"))

    def altera_metrico(self):
        _translate = QtCore.QCoreApplication.translate
        # Alteração das informações de entrada
        self.boxSaida.setItemText(1, _translate("MainWindow", "KM"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "Jardas"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "Polegadas"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "Pes"))
        # Alteração das informações de entrada
        self.boxEntrada.setItemText(1, _translate("MainWindow", "KM"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "Jardas"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "Polegadas"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "Pes"))
        # Variavel de controle
        self.currentActive = 'metrico'
        self.label.setText(_translate("MainWindow", "CONVERTER MEDIDAS"))
