# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 160)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.boxSaida = QtWidgets.QComboBox(self.centralwidget)
        self.boxSaida.setObjectName("boxSaida")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.boxSaida.addItem("")
        self.gridLayout.addWidget(self.boxSaida, 3, 0, 1, 2)
        self.btnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.btnConvert.setObjectName("btnConvert")
        self.gridLayout.addWidget(self.btnConvert, 6, 1, 1, 1)
        self.boxEntrada = QtWidgets.QComboBox(self.centralwidget)
        self.boxEntrada.setObjectName("boxEntrada")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.boxEntrada.addItem("")
        self.gridLayout.addWidget(self.boxEntrada, 1, 0, 1, 2)
        self.lineValorIn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineValorIn.setText("")
        self.lineValorIn.setObjectName("lineValorIn")
        self.gridLayout.addWidget(self.lineValorIn, 6, 0, 1, 1)
        self.lineResultado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineResultado.setText("")
        self.lineResultado.setReadOnly(True)
        self.lineResultado.setObjectName("lineResultado")
        self.gridLayout.addWidget(self.lineResultado, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 394, 21))
        self.menubar.setObjectName("menubar")
        self.menuTipo_de_dado = QtWidgets.QMenu(self.menubar)
        self.menuTipo_de_dado.setObjectName("menuTipo_de_dado")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDados_de_arm = QtWidgets.QAction(MainWindow)
        self.actionDados_de_arm.setObjectName("actionDados_de_arm")
        self.actionMoeda = QtWidgets.QAction(MainWindow)
        self.actionMoeda.setObjectName("actionMoeda")
        self.actionMetrico = QtWidgets.QAction(MainWindow)
        self.actionMetrico.setObjectName("actionMetrico")
        self.menuTipo_de_dado.addAction(self.actionDados_de_arm)
        self.menuTipo_de_dado.addAction(self.actionMoeda)
        self.menuTipo_de_dado.addAction(self.actionMetrico)
        self.menubar.addAction(self.menuTipo_de_dado.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boxSaida.setItemText(0, _translate("MainWindow", "Escolha o tipo de saida"))
        self.boxSaida.setItemText(1, _translate("MainWindow", "MB"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "KB"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "Kb"))
        self.btnConvert.setText(_translate("MainWindow", "Converter"))
        self.boxEntrada.setItemText(0, _translate("MainWindow", "Escolha o tipo de entrada"))
        self.boxEntrada.setItemText(1, _translate("MainWindow", "MB"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "Mb"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "KB"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "Kb"))
        self.lineValorIn.setPlaceholderText(_translate("MainWindow", "Insira um valor"))
        self.lineResultado.setPlaceholderText(_translate("MainWindow", "Resultado"))
        self.menuTipo_de_dado.setTitle(_translate("MainWindow", "Tipo de dado"))
        self.actionDados_de_arm.setText(_translate("MainWindow", "Dados de arm."))
        self.actionMoeda.setText(_translate("MainWindow", "Moeda"))
        self.actionMetrico.setText(_translate("MainWindow", "Metrico"))

    def altera_moedas(self):
        _translate = QtCore.QCoreApplication.translate
        # Alteração das informações de entrada
        self.boxEntrada.setItemText(1, _translate("MainWindow", "R$"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "ER"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "$"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "Libras"))
        # Alteração das informações de saida
        self.boxSaida.setItemText(1, _translate("MainWindow", "R$"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "ER"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "$"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "Libras"))

    def altera_dados(self):
        _translate = QtCore.QCoreApplication.translate
        # Alteração das informações de entrada
        self.boxSaida.setItemText(1, _translate("MainWindow", "BRL"))
        self.boxSaida.setItemText(2, _translate("MainWindow", "USD"))
        self.boxSaida.setItemText(3, _translate("MainWindow", "JPY"))
        self.boxSaida.setItemText(4, _translate("MainWindow", "EUR"))
        # Alteração das informações de entrada
        self.boxEntrada.setItemText(1, _translate("MainWindow", "BRL"))
        self.boxEntrada.setItemText(2, _translate("MainWindow", "USD"))
        self.boxEntrada.setItemText(3, _translate("MainWindow", "JPY"))
        self.boxEntrada.setItemText(4, _translate("MainWindow", "EUR"))

    def altera_metrico(self):
        # TODO: implent method to convert measures
        pass
